services:
  meterreadings:
    image: meterreadings
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=MeterReadingsDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
      - APP_UID=1000
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sqlserver
      
  vueapp:
    build:
      context: ./meterreadings-ui 
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - meterreadings
      
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}
    restart: unless-stopped
